version: '3.5'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: etherpad/etherpad:1.8.6
        restart: ${RESTART_POLICY:-unless-stopped}
        environment:
            - TITLE=${ETHERPAD_TITLE}
            - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
            - SKIN_NAME=${ETHERPAD_SKIN_NAME}
            - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
            - ADMIN_PASSWORD=Your_PASSWOR
            - USER_PASSWORD=Your_PASSWOR
            - DB_TYPE=postgres
            - DB_HOST=eatherpaddb
            - DB_PORT=5432
            - DB_NAME=etherpadb
            - DB_USER=etherpad
            - DB_PASS=Your_PASSWORD
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
    eatherpaddb:
        image: postgres:13
        restart: always
        command: postgres -c stats_temp_directory=/tmp & chown -R
        environment:
            - POSTGRES_DB=etherpadb
            - POSTGRES_USER=etherpad
            - POSTGRES_PASSWORD=Your_PASSWORD
        volumes:
            - ./jitsi-meet-cfg/etherpad/_data:/var/lib/postgresql/data/  
        networks:
            meet.jitsi:
